language: nix
script: nix-build
sudo: true
before_deploy:
  - git config --local uesr.name "Masayuki Takeda"
  - git config --local user.email "mtakeda.enigsol@gmail.com"
  - git tag "$(date +'%F')-$(git log --format=%h -1)"
deploy:
  provider: releases
  api_key:
    secure: hgYOg3oHDnWWKvc1Hg7WggpQ+bsRmco24bUdY5uoG3JctQVn86K7gY8i8viro/KmR7S0/k0k+dQQeZcnYEa0DM+nscD20Qm1dF6JQ0VzTFhdTx+6in4ndE89c/TYnhm1ozaxJ/8p5vF0Cp5Ob6CfdXmiK7bpHznu9KNLHW6/QPb3pCKN2sSNY9JE2lGTSRgHzfYKUDefnxfKo/g1i+pho5lXIXrsTeL0qX8IqMmcon6Qu1GHFJllc9zdjugST92Mv+4avRdxlqQdcMqAW616AWs2knZwO/RYHLKjLtqdhrADTrGFHQb/eQCMzPws65wDS2kc9788lnYO6aqQJgheUyHdOq/zALqW9pStilkdmiiPa/+8L5kuePE/qcD03EhFRKuQoTbziOlbQAULedXzM6yanuImKMT9zhKQPZuWlCjeBnbYwcnsvFDizC9JtDgmyjrsuok6dFDPBDJOfArYYB4+uJpsqsTIu+WZSW4KWgTjk36RK0n+Uw1tVxCpsuq+GW6M1StxBqmw8r49OQQmUFUk7+ukT2loDeymoHy3/ruqzElObyysqwG8T9cHgYR1JKVMIyxJ2/DTeonSq+pw8Hx0uCydSVbpXI0e/Rnvdf/UW3DG0h5ZehoIqFzR4v3YhYm2qDRxpidQzYlPzmUBDFrk3sRvI+Jh7ty0006MSoU=
  file: result/rule.pdf
  skip_cleanup: true
